[14.0][ADD] account_advance: add new module
Escodoo/account-addons pull request #73
Opened 2024-06-04 12:48 UTC by kaynnan

cc @marcelsavegnago @douglascstd @WesleyOliveira98 @Matthwhy

2024-06-04 14:07 UTC, marcelsavegnago commented
talvez melhor mudar o nome para account_payment_advance

2024-06-04 16:52 UTC, douglascstd commented
Nao incluiria o Payment no nome... pois nao tem pagamento...
Acho melhor usar o compensate

2024-06-04 16:59 UTC, kaynnan commented
Então ficaria account_compensate_advance?

2024-06-04 17:26 UTC, marcelsavegnago commented
> account_compensate_advance

por mim ok

2024-06-04 17:49 UTC, kaynnan commented
Concluída a renomeação, assim que todos derem o OK do módulo, subo um novo commit com a tradução pt_BR

2024-06-04 20:37 UTC, douglascstd commented on account_compensate_advance/README.rst
> +  * Douglas Custodio <douglas.custodio@escodoo.com.br>
douglascstd@yahoo.com - é o meu login do github ;-)

2024-06-04 20:40 UTC, kaynnan commented on account_compensate_advance/README.rst
> +  * Douglas Custodio <douglas.custodio@escodoo.com.br>
Certo, realizei a alteração.

2024-06-04 21:58 UTC, marcelsavegnago commented on account_compensate_advance/readme/CONTRIBUTORS.rst
> +  * Douglas Custodio <douglascstd@yahoo.com>
aqui pode manter o da escodoo mesmo.. ele nao associa com a conta do git.. soh se for colocar como mantenedor do manifesto.. ai sim coloca o user do github.

2024-06-07 13:38 UTC, WesleyOliveira98 approved these changes
LGTM

2024-06-12 18:30 UTC, douglascstd requested changes
[FUNCIONTAL REVIEW] REPROVED

O account.move tem que ser abastecido com o res.partner inserido no form
![image](https://github.com/Escodoo/account-addons/assets/20867090/a6db9dd1-d3fe-411e-a4ba-489dd0e70180)
![image](https://github.com/Escodoo/account-addons/assets/20867090/f8df4caf-03a0-4a4a-a7c6-6b36f1ae3191)
![image](https://github.com/Escodoo/account-addons/assets/20867090/41137edd-b713-4b38-a18c-d8a40c083526)

Não está aparecendo nenhum registro de adiantamento.
![image](https://github.com/Escodoo/account-addons/assets/20867090/1ee68e45-f88e-41c4-85c4-79d39d93ebb5)
![image](https://github.com/Escodoo/account-addons/assets/20867090/ccce2b39-5956-4830-a639-e2a74152ef8d)
Encontrei o erro, que ao criar uma conta de adiantamento pela interface:

Ele não marca que o campo "Reconciliavel" da conta, mas mesmo assim ele deixa essa conta no registro do diário:
![image](https://github.com/Escodoo/account-addons/assets/20867090/f163358c-f9b2-4c85-8203-311f49880d6b)

---
**Erro na compensação:**
Ao selecionar um adiantamento realizado, ele não permitiu fazer a compensação:
![image](https://github.com/Escodoo/account-addons/assets/20867090/eedd01aa-0c30-448e-8307-8b82800eced7)
![image](https://github.com/Escodoo/account-addons/assets/20867090/5d12216c-cb16-4ea2-88fe-eda3450f5e3b)

2024-06-13 12:21 UTC, WesleyOliveira98 approved these changes

2024-06-13 19:35 UTC, douglascstd reviewed
1. Só pode ser utilizado um adiantamento que já foi quitado no banco. Para selecionar ele para Compensar, a contra partida deve estar FULL RECONCILED...


2. Para selecionar um adiantamento, fica visualmente mais fácil se puder adicionar (Data / Total / Saldo)
![image](https://github.com/Escodoo/account-addons/assets/20867090/5fcd8cd0-9c94-42d7-95cb-659e40ba3895)


3. O botão de Criar na view do tipo Tree não está abrindo o Wizard.
![image](https://github.com/Escodoo/account-addons/assets/20867090/5aa32c47-7403-4cbf-949c-5b412c328ecd)


4. A data da criação do lançamento de Compensação não está respeitando a data do Adiantamento
![image](https://github.com/Escodoo/account-addons/assets/20867090/633d17ba-f064-4898-9334-b2448a91b6c3)

5. Na View de lançamentos de Adiantamentos aparecem os Adiantamentos e Compensação realizadas, Precisa ter uma forma de filtrar esses lançamentos (sugestão, que é semelhante ao módulo de juntar adiantamentos do expense, é incluir um campo tipo bollean marcando o que é adiantamento) - Criar um filtro para ser possível marcar
![image](https://github.com/Escodoo/account-addons/assets/20867090/361ce49d-b996-427e-8c42-c40660b1073b)

6. O Status dos Adiantamentos so apresenta se eles estão ou não lançados, mas deveriamos ter um status: Não Pago, Pago, Parcialmente Compensado, Compensado
**Não Pago**: account.mole.line da Contas a Pagar/Receber NAO está totalmente reconciliado
**Pago**: account.mole.line da Contas a Pagar/Receber está totalmente reconciliado
**Parcialmente Compensado**: account.mole.line da Conta de Adiantamento NAO está totalmente reconciliado
**Pago**: account.mole.line da Conta de Adiantamento está totalmente reconciliado
Incluir um filtro também destes status

2024-06-14 14:59 UTC, douglascstd commented
Observando melhor o processo, onde a criação do adiantamento pode ser feito pela fatura ou até mesmo por um lançamento de diário avulso. 
Desta forma pode ser retirado o wizard de criação de adiantamento e concentrar o módulo somente na questão da compensação...

2024-06-14 20:13 UTC, kaynnan commented
Pessoal deixei em draft ainda por conta que falta eu terminar a refatoração em questão de usabilidade, assim que eu finalizar coloco a PR para revisar

2024-06-21 19:24 UTC, kaynnan commented
Estou finalizando a tradução com o arquivo .pot, em breve subo o commit

2024-06-23 22:11 UTC, kaynnan commented
Ultimo commit foi incluído:

1. Mensagem semelhante ao Payment Register quando há pagamentos disponíveis para o cliente / fornecedor, porém, adaptado para a compensação de adiantamento.
2.  Ajustes na tradução pt_BR

2024-06-23 22:14 UTC, kaynnan commented
ping @Escodoo/consultores @Escodoo/desenvolvedores

2024-06-24 19:16 UTC, marcelsavegnago approved these changes

2024-06-24 19:16 UTC, merged